# Supabase 설정
SUPABASE_URL = ""
SUPABASE_KEY = ""
OPENAI_API_KEY = "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"